# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20160907_1439'),
        ('matricula', '0002_auto_20160908_1757'),
    ]

    operations = [
    ]
